name = "amina"
compatibility_date = "2025-04-1"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"
upload_source_maps = true

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true
